### ISSUE TITLE
ML: Listen folder, detect & blur

### ISSUE THREAD

**Issue by punov** [Hivemapper/hdc_firmware#158]
Create service to listen for folder /mnt/data/unprocessed_framekm

And once there's new FrameKM package,
- read every frame from it with the cursor
- run resize, inference & masking for every frame,
- prepare JSON file containing the following information for every processed frame:
  - resizing time
  - inference time
  - masking time
  - hash of model weights
  - class id
  - confidence 
  - bounding box info (cx, cy, width, height)
  - with name of the JSON similar to name of the FrameKM but with '.json' extension
- packing all the processed frames into new frameKM in /mnt/data/framekm folder
- dropping metadata JSON into /mnt/data/ml_metadata

**Comment by Eduard-Voiculescu** [comment]
Currently there is not much error handling. 
- add error handling when creating and moving files

Also, the python chime only works on newly created framekm files. Do we want to extend that to already existing framekms?
