### ISSUE TITLE
USB stick directory & imagery

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/hdc_firmware#167]
- Create directory with subfolder by date (truncated day)
- Include telemetry, currently missing location data (IMU, GNSS)

**Comment by evanmoss** [comment]
Simple solution ideas: just have a cron job that does:

Both require the odc-api to be aware if a flashdrive is plugged in, which it should know how to do 

Via ODC-API **if flashdrive is plugged in**:
1. list directory of images (jpg files that aren't folders)
2. group by days
3. mv files to appropriate folder

Simple solution idea for (2): 
Via ODC-API **if flashdrive is plugged in**:
1. Every time the odc-api scans a imu or gnss file, just copy it if it doesn't exist on the flashdrive

**Comment by evanmoss** [comment]
cc @punov for situational awareness on aboe

**Comment by punov** [comment]
@evanmoss sure, makes sense to me!
We'll start with #2, I will think a bit on #1: 
even listing USB directory takes a lot of time, so I have couple ideas for this one how to make it in optimal way
.

**Comment by jayalberts** [comment]
still investigating.

**Comment by jayalberts** [comment]
focus on moving images first, then back to location data

**Comment by HariHive** [comment]
for images: PR: https://github.com/Hivemapper/odc-api/pull/95

**Comment by jayalberts** [comment]
usb is crashing odc-api and hari is implementing and testing a fix.

**Comment by jayalberts** [comment]
hari working through PR comments

ODCAPI is trying to move images again that have already been transferred, still need to investigate. Doesn't happen on small amount of images, only larger amounts.

**Comment by jayalberts** [comment]
@HariHive to add validation steps
