### ISSUE TITLE
Validate skip_4k option for HDC / USB

### ISSUE THREAD

**Issue by punov** [Hivemapper/hdc_firmware#174]
camera-bridge commit to validate: c2665551ac19a7a986c67d822c4da49323337f80
- Check CPU usage
- Check USB writing + format + FPS (media/usb0/recording)
- check HDC imagery format + FPS (tmp/recording/pic)

**Comment by punov** [comment]
@jayalberts we'll need to squeeze it into 3.5:
it's a very optimisation for camera so we'll not lack CPU resources once we roll out ML

**Comment by jayalberts** [comment]
no longer applicable. fixed in 3.9 and 4.2 HDC
