### ISSUE TITLE
USB Stick Writing Fix (Configurable FPS)

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/hdc_firmware#193]
Evan to add suggestion

**Current Issue**
- Plugging in USB:
    - Camera FPS: 0-4fps
    - USB Stick: 0-2fps 
- Based on USB Stick Write Speed:
    - HDC production: 2 fps
    - other, lower-end memory: 0 fps sometimes

**Acceptance Criteria**
- Camera reaches 10fps
	- Essentially, the same as the HDC without USB
- Without Plug:
	- 10fps on the Camera
- With Plug:
	- Camera FPS: 10
	- USB FPS: "Decent FPS" Range
		- Minimum 5
		- And more if possible
	- We at least want an improvement over the current 1-2 fps

**Additional Notes**
- We use timestamps to determine what XX:SS the frame was written
- We can use SSH (`ls -wcl` to count the image delta over time)

**Comment by evanmoss** [comment]
@HariHive Here is a simple approach to reduce write throughput to USB by 50%
```
bool skippedLastFrameForUSB = false;

if (!skippedLastFrameForUSB) {
  skippedLastFrameForUSB = true;
} else {
  // do write to usb
}
```

**Comment by jayalberts** [comment]
got build file yesterday from Alexei, started testing.

try to do USB 5 FPS and hivemapping 10 FPS? See if it will work.

**Comment by jayalberts** [comment]
dropping every other image didn't help with FPS (~2). Tried every 5th and FPS was closer to 10. 

Writing speed of USB matter. Validate with JT's USB.

Next step: more testing and validate with metrics.

**Comment by jayalberts** [comment]
masaya has test written for this

**Comment by jayalberts** [comment]
archive this as duplicate of https://github.com/Hivemapper/camera_bridge/issues/9
