### ISSUE TITLE
HDC stops recording randomly

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/hdc_firmware#208]
Camera will be going fine for hours, then stop recording. Three lights on. Camera view in app still updates as normal. Only way to save cam and continue hivemapping is to reboot. After reboot, no new data is sent to phone related to the sections driven while recording had stopped.

Reported on Discord by community testers 

- Koen `great-periwinkle-ice`
- Eddie `hopeful-brown-bluebird`
- GatorMine `sharp-champagne-pig`

**Comment by jayalberts** [comment]
Mazar investigating logs, might not be related to changes he made.

@jayalberts double check if USB plugged in and exact timestamps.

**Comment by jayalberts** [comment]
All times PST

Eddie stopped recording 1/19 approx 11:20-11:40 and 1/18 approx 10:40-11:00.

Koen stopped recording on 1/20 sometime before 2:30 PST

Gator stopped recording on 1/20 sometime probably around or after 9:00 PST

Both Gator and Koen reported app crashing when trying to send DB. Seems to point to some issue with camera DB perhaps?

**Comment by mazar-farran** [comment]
Did Koen and Gator use a USB?

**Comment by mazar-farran** [comment]
Also, to be 100% sure, all three testers reported the camera view was still showing images?

**Comment by Masaya-RT** [comment]
Today I drove on 3.9.1 for about an hour, with USB attached.
- USB recorded normally
- FrameKms uploaded normally

Caveat - Didn't clock several hours like the community testers

**Comment by jayalberts** [comment]
@mazar-farran 

Koen: confirmed 3 lights on dashcam and image preview on app
Gator: confirmed 3 lights on dashcam and image preview on app
Eddie: confirmed 3 lights on dashcam but he doesn't use dashcam tab (only map) so can't determine if preview was showing

**Comment by mazar-farran** [comment]
@punov image preview on app indicates that camera bridge is unlikely to be the problem.  I found some gaps in the DashcamPackedFrameKm updates on Mode (attached in slack).  But those times also do not seem to all line up with the reported recording times.  Could you take a look at this? Thank you

great-periwinkle-ice gap between 12:32 and 14:04 UTC
hopeful-brown-bluebird gap between 19:20 and 19:40 UTC (as reported) (logs show "TRAVELLED TOO FAR" and "Not enough frames to add yet" messages).
sharp-champagne-pig gap between 20:11 and 22:42 UTC, another smaller one between 17:02 and 17:30 UTC

**Comment by jayalberts** [comment]
Another user (Dragon666 on Discord) to investigate with same issue. Collecting more info now.

**Comment by jayalberts** [comment]
Mazar investigated further, no smoking gun.

**Comment by jayalberts** [comment]
No common cause, all slightly different. At least one user with reliability of GNSS logger.

**Comment by jayalberts** [comment]
This might have been related to db issues which were resolved in 4.2. Closing out
