### ISSUE TITLE
HDC CICD

### ISSUE THREAD

**Issue by punov** [Hivemapper/hdc_firmware#212]
Goal of this task to make HDC deployment easy and protect us from stupid mistakes.

- It should be easy to deploy new HDC including necessary version of ODC API using a single command / single action
- It should be easy to uptick the version of the build without a need to do a lot of steps

Action Items:
For ODC API repository: 
- Setting up a github action to ODC API project for adding a tag
- Once tag added, building ODC API and triggering the build for HDC firmware containing this version of ODC API
- Once rauc file is ready, upload it to S3

For HDC repository:
- Once tag added, fetching the version of ODC API with added, or if doesn't exist - building uptick ODC API version and including it to the project
- Executing clean make
- Once rauc file is ready, upload it to S3

**Comment by punov** [comment]
Take a look at WIP for it started a year ago:
https://github.com/Hivemapper/hdc_firmware/tree/main/.github/workflows

**Comment by Masaya-RT** [comment]
Starting this today

**Comment by Masaya-RT** [comment]
Firmware is uploading correctly
-uncompressed
-naming matches ok

Might need some additional permissions for the CTP bucket

**Comment by Masaya-RT** [comment]
PR created

**Comment by mazar-farran** [comment]
Done
