### ISSUE TITLE
Testing new models 1x2

### ISSUE THREAD

**Issue by jayalberts** [Hivemapper/hdc_firmware#223]

**Comment by jayalberts** [comment]
seeing huge boost in performance. will help at lower speeds.

**Comment by Masaya-RT** [comment]
Did a QA drive using HDC FW 4.4.10.
- Also deployed to 2 city-heavy CTP drivers
- Pending visual validation

**Comment by jayalberts** [comment]
recent metrics are optimistic for 800 model
although a little slower
removed CPU limiters to see what performance we can squeeze, looks stable and metrics ok
collects debt on highway but need more data
working on visual validation today

**Comment by Masaya-RT** [comment]
Pushing camera to the new limit
New big models are keeping up with the pace "just fine" (not good)
- everything else is deteriorating as a result (GNSS and FPS reduction)
- Ended up being more chunking on FrameKm size (ML OK, chunking bad)
- Deteriorations seen across 10 Users (CTP)
Evan: Can we further limit the CPU usage? Yes, but will probably be critically slow
- Cap inferrence to CPU and leverage other resources for other tasks?
- Make these configurable for rapid experimentation

n800 is still being validated - needs more scenarios

**Comment by Masaya-RT** [comment]
Backlogs are OK, prioritize ML + FPS
