### ISSUE TITLE
Improve HDC Firmware build process

### ISSUE THREAD

**Issue by mazar-farran** [Hivemapper/hdc_firmware#225]
Firmware build process is suboptimal.  To incorporate changes on odc-api, data-logger, gnss, and imu, we need to either a) host a new release on github for that specific component or b) hack a change locally (e.g. using sed to bump the firmware version in the compiled odc-api).  Both of these approaches are time consuming and highly error prone.

Ideally `buildroot` and `yocto` would grab the source code from a specified commit and build it from scratch.  This avoids the unnecessary step of packaging and hosting a new release.  It also allows you to make local changes to the source itself (e.g. by using `devtool modify` for yocto) instead of trying to patch the binaries.

This ticket is specifically for work on the HDC firmware

**Comment by jayalberts** [comment]
data logger building from source for HDC, should simplify

**Comment by Masaya-RT** [comment]
Able to get odc-api building from source for the HDC firmware build

**Comment by Masaya-RT** [comment]
Found some camera-node issues related to changes. Found a workaround, should be pretty much good to go for getting Build-from-Source working

**Comment by Masaya-RT** [comment]
More work on Camera-node build
- Found better, more robust method than previous workaround
- no longer requires pre-compiled SQLite library

**Comment by jayalberts** [comment]
ready to be merged, Alexei review
