### ISSUE TITLE
4.4.20 - "+ ML" Suffix was not added to a batch of FrameKms on March 17th

### ISSUE THREAD

**Issue by Masaya-RT** [Hivemapper/hdc_firmware#234]

**Comment by Masaya-RT** [comment]
CTP Users:
- mattcintosh : spicy-strawberry-pear
- mishmear : glistening-magenta-sculptor

https://github.com/Hivemapper/hdc_firmware/assets/152318264/3d24b8e6-4218-4ff4-b48a-6eac41596eb8

**Comment by jayalberts** [comment]
check these images specifically

**Comment by Masaya-RT** [comment]
{"isRunningInBackground":false,"isInvokedFromSilentPush":false,"name":"km_20240317_180515_125_0","numFrames":125,"id":"65f82003d7cc47a15e6a2536"} - According to Nick, there is no privacy model hash on the framekm
