### ISSUE TITLE
Populate DB file with only necessary GNSS Auth data, at a reasonable interval

### ISSUE THREAD

**Issue by Masaya-RT** [Hivemapper/hdc_firmware#239]
Currently, this is behind a feature flag for CTP-only.
- Before we release to production, we should only include in database at a reasonable rate

Currently enters every 1 second. We should slow down the frequency of request.

Perhaps purge the GNSS Auth data more frequently, in addition to slower frequency.

**Comment by mazar-farran** [comment]
Merged https://github.com/Hivemapper/hivemapper-data-logger/pull/11.  @punov will deploy the fix for testing.

HDC 4.5.4

**Comment by mazar-farran** [comment]
Fixed by https://github.com/Hivemapper/hivemapper-data-logger/pull/11
